name: charnacoin
version: 0.10.2-1
summary: "Charnacoin: the modern, secure, easy crypto currency solution https://charnacoin.com"
description: |
    Charnacoin is a new cryptocurrency based on CryptoNote technology. 
    It's major benefit is to provide much stronger privacy to both the senders and receivers of transactions. 
    With Charnacoin, you are your own bank. 
    Only you control and are responsible for your funds, and your accounts and transactions are kept private from prying eyes. 
grade: devel
confinement: strict

apps:
    charnacoind:
        daemon: forking
        command: |
          charnacoind-wrapper --detach --data-dir ${SNAP_COMMON} --config-file ${SNAP_USER_DATA}/etc/charnacoind.conf
        plugs:
            - network
            - network-bind
    charnacoin-wallet-rpc:
        command: |
          charnacoin-wallet-rpc --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network
            - network-bind
    charnacoin-wallet-cli:
        command: |
          charnacoin-wallet-cli --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network

parts:
    cmake-build:
        plugin: cmake
        configflags:
            - -DBDB_STATIC=1
            - -DUPNP_STATIC=1
            - -DBoost_USE_STATIC_LIBS=1
            - -DBoost_USE_STATIC_RUNTIME=1
            - -DARCH=default
        source: .
        build-packages:
            - gcc
            - pkg-config
            - libunbound-dev
            - libevent-dev
            - libboost-all-dev
            - libdb-dev
            - libunwind-dev
            - libminiupnpc-dev
            - libldns-dev
            - libexpat1-dev
            - bison
            - doxygen
            - graphviz
        stage-packages:
            - libminiupnpc10
            - libunbound2
            - libunwind8
        prime:
            - bin
            - usr/lib/
            - -usr/lib/gcc
            - -usr/share

    dist-files:
        plugin: dump
        source: .
        organize:
            contrib/snap/charnacoind.conf: etc/charnacoind.conf
            contrib/snap/charnacoind-wrapper: bin/charnacoind-wrapper
        prime:
            - etc
            - bin
